# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: GitHubStarStatusUpdate

on:
  push:
    branches:
      - dev
    # paths:
    # # Trigger only when src/** changes
    #   - "README_template.md"
    #   - "config.json"
  # 请将该文件放到默认分支,因为schedule只在默认分支生效
  # https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#onschedule
  schedule: 
       - cron: '1 0 * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - name: Checkout default branch to ./public
      uses: actions/checkout@v2
      with:
        ref: master
        path: public

    - name: Checkout dev branch to ./dev
      uses: actions/checkout@v2
      with:
        ref: dev
        path: dev

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install matplotlib==3.3.4
        pip install requests==2.22.0
        pip install Jinja2==2.11.2
        pip install MarkupSafe==1.1.1
        
    - name: run tasks
      env:
        MY_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd dev
        python main.py config.json
        if [ ! -d ../public/data ]; then mkdir ../public/data; fi
        cp -rf ./data ../public
        mv -f README.md ../public/README.md

    - name: commit
      id: commit
      run: |
        cd public
        git config --global user.email github-actions@github.com
        git config --global user.name github-actions
        git add ./data
        git add README.md
        git commit -m "update by action_bot"
        git push
      continue-on-error: true
